In [3]:
import pandas as pd
import numpy as np
import missingno as msno
from jupyter_server.nbconvert.handlers import date_format

airbnb = pd.read_csv("../data/airbnb.csv")

# help(())

In [115]:
# airbnb.shape
# airbnb.head(5)
# airbnb.tail(5)
airbnb.info()
# airbnb.describe()
# airbnb.isnull().sum()
# airbnb.duplicated().sum()
# airbnb.describe()
# airbnb[~airbnb['price'].str.contains('$', regex=False)]
# airbnb[ (~airbnb['price'].str.contains('$', regex=False, na=False)) & (airbnb['price'].notna()) ]
# airbnb.isnull().sum()

<class 'pandas.DataFrame'>
RangeIndex: 10019 entries, 0 to 10018
Data columns (total 17 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Unnamed: 0          10019 non-null  int64
 1   listing_id          10019 non-null  int64
 2   name                10014 non-null  str
 3   host_id             10019 non-null  int64
 4   host_name           10017 non-null  str
 5   neighbourhood_full  10019 non-null  str
 6   coordinates         10019 non-null  str
 7   room_type           10019 non-null  str
 8   price               9781 non-null   str
 9   number_of_reviews   10019 non-null  int64
 10  last_review         7944 non-null   str
 11  reviews_per_month   7944 non-null   float64
 12  availability_365    10019 non-null  int64
 13  rating              7944 non-null   float64
 14  number_of_stays     7944 non-null   float64
 15  5_stars             7944 non-null   float64
 16  listing_added       10019 non-null  str
dtypes: float64(4), int64(5), str(8)
memory usage: 1.3 MB

In [116]:
# msno.matrix(airbnb)
# msno.bar(airbnb)
# msno.dendrogram(airbnb)

In [117]:
airbnb
# airbnb.isnull().sum()

,Unnamed: 0,listing_id,name,host_id,host_name,neighbourhood_full,coordinates,room_type,price,number_of_reviews,last_review,reviews_per_month,availability_365,rating,number_of_stays,5_stars,listing_added
0,0,13740704,"Cozy,budget friendly, cable inc, private entra...",20583125,Michel,"Brooklyn, Flatlands","(40.63222, -73.93398)",Private room,45$,10,2018-12-12,0.70,85,4.100954,12.0,0.609432,2018-06-08
1,1,22005115,Two floor apartment near Central Park,82746113,Cecilia,"Manhattan, Upper West Side","(40.78761, -73.96862)",Entire home/apt,135$,1,2019-06-30,1.00,145,3.367600,1.2,0.746135,2018-12-25
2,2,21667615,Beautiful 1BR in Brooklyn Heights,78251,Leslie,"Brooklyn, Brooklyn Heights","(40.7007, -73.99517)",Entire home/apt,150$,0,NaN,NaN,65,NaN,NaN,NaN,2018-08-15
3,3,6425850,"Spacious, charming studio",32715865,Yelena,"Manhattan, Upper West Side","(40.79169, -73.97498)",Entire home/apt,86$,5,2017-09-23,0.13,0,4.763203,6.0,0.769947,2017-03-20
4,4,22986519,Bedroom on the lively Lower East Side,154262349,Brooke,"Manhattan, Lower East Side","(40.71884, -73.98354)",Private room,160$,23,2019-06-12,2.29,102,3.822591,27.6,0.649383,2020-10-23
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10014,10014,22307861,Lovely 1BR Harlem apartment,16004068,Rachel,"Manhattan, Harlem","(40.80379, -73.95257)",Entire home/apt,105$,4,2018-05-28,0.21,0,4.757555,4.8,0.639223,2017-11-22
10015,10015,953275,Apartment For Your Holidays in NYC!,4460034,Alain,"Manhattan, East Harlem","(40.79531, -73.9333)",Entire home/apt,125$,50,2018-05-06,0.66,188,4.344704,60.0,0.648778,2017-10-31
10016,10016,3452835,"Artsy, Garden Getaway in Central Brooklyn",666862,Amy,"Brooklyn, Clinton Hill","(40.68266, -73.96743000000002)",Entire home/apt,100$,45,2016-11-27,0.98,0,3.966214,54.0,0.631713,2016-05-24
10017,10017,23540194,"Immaculate townhouse in Clinton Hill, Brooklyn",67176930,Sophie,"Brooklyn, Clinton Hill","(40.68832, -73.96366)",Entire home/apt,450$,2,2019-05-31,0.17,99,4.078581,2.4,0.703360,2018-11-25
10018,10018,32876011,Private room in a perfect location in the city,59583716,Shai,"Manhattan, Upper East Side","(40.76174, -73.96625)",Private room,90$,1,2019-03-12,0.25,8,4.069096,1.2,0.720249,2018-09-06


# Plan Czyszczenia Zbioru Danych (Airbnb)

## Faza 1: Zrzucenie Balastu (Quick Wins)
W tej fazie pozbywamy się śmieci, które tylko zżerają pamięć i zaburzają statystyki.
- [ ] **Usunięcie bezużytecznych kolumn:** Wyrzucenie kolumny `Unnamed: 0` (pozostałość po starym indeksie).
- [ ] **Usunięcie klonów:** Sprawdzenie i usunięcie zduplikowanych wierszy w skali 1:1 (ta sama oferta skopiowana dwa razy).

## Faza 2: Transformacja Typów Danych (Rzutowanie)
W tej fazie zmuszamy Pandas do poprawnego rozumienia liczb i dat.
- [ ] **`price`:** Wycięcie symbolu waluty (`$`) i konwersja kolumny ze zmiennej tekstowej na liczbową (`float`).
- [ ] **`number_of_stays`:** Konwersja na liczby całkowite (`int`) – usunięcie wartości po przecinku.
- [ ] **`listing_added` & `last_review`:** Konwersja ze zwykłego tekstu na format daty (`datetime`).

## Faza 3: Inżynieria Cech (Rozbijanie tekstu)
W tej fazie wyciągamy użyteczne informacje z brudnych ciągów znaków.
- [ ] **`coordinates`:** Rozbicie nawiasu i podział na dwie osobne kolumny numeryczne: `latitude` i `longitude`.
- [ ] **`neighbourhood_full`:** Rozdzielenie tekstu po przecinku na dwie nowe kolumny: `city` oraz `neighbourhood`.
- [ ] **`room_type`:** Ujednolicenie kategorii (np. "private room" i "private" -> jedna nazwa).

## Faza 4: Obsługa Braków Danych (Missing Values)
W tej fazie łatamy dziury w bazie.
- [ ] **Weryfikacja 2075 braków:** Sprawdzenie, czy braki w ocenach wynikają z braku recenzji (`number_of_reviews == 0`).
- [ ] **Uzupełnianie luk:** Decyzja o uzupełnieniu lub usunięciu braków w `price` (238), `name` (5) i `host_name` (2).

## Faza 5: Walidacja Logiki Biznesowej (Sanity Checks)
W tej fazie sprawdzamy, czy dane nie łamią praw fizyki i logiki ekonomicznej.
- [ ] **Test kalendarza:** Sprawdzenie `availability_365` pod kątem wartości ujemnych lub > 365.
- [ ] **Test chronologii:** Sprawdzenie, czy `last_review` nie jest starsze niż `listing_added`.
- [ ] **Test skali ocen:** Sprawdzenie, czy `rating` i `5_stars` mieszczą się w poprawnym przedziale (np. 1-5).

## Faza 1 dropy

In [4]:
airbnb = airbnb.drop(columns=['Unnamed: 0'] , errors='ignore')
airbnb = airbnb.drop_duplicates()

## Faza 2 transformacja typów

In [5]:
airbnb['price'] = airbnb['price'].str.replace('$', '', regex=False).astype('float64')
airbnb['number_of_stays'] = airbnb['number_of_stays'].astype('Int64')
airbnb['listing_added'] = pd.to_datetime(airbnb['listing_added'])
airbnb['last_review'] = pd.to_datetime(airbnb['last_review'])
# print(airbnb[['price', 'number_of_stays', 'listing_added', 'last_review']].dtypes)
# airbnb

TypeError: cannot safely cast non-equivalent float64 to int64

## Faza 3  rozbijanie i poprawianie  danych

In [6]:
airbnb[['latitude', 'longitude']] = airbnb['coordinates'].str.strip('()').str.split(', ', expand=True).astype(float)
airbnb[['town','district']] = airbnb['neighbourhood_full'].str.split(', ' , expand=True)
airbnb['room_type'] = airbnb['room_type'].replace('private', 'Private room')
airbnb['room_type'] = airbnb['room_type'].replace('Private', 'Private room')
airbnb['room_type'] = airbnb['room_type'].replace('PRIVATE ROOM', 'Private room')
airbnb['room_type'] = airbnb['room_type'].replace('   Shared room      ', 'Shared room')
airbnb = airbnb.drop(columns=['coordinates', 'neighbourhood_full'])
airbnb['room_type'].unique()

<StringArray>
['Private room', 'Entire home/apt', 'Shared room', 'home']
Length: 4, dtype: str

## Faza 4 obsługa Nan

In [126]:
# airbnb[airbnb['name'].isna()]
airbnb = airbnb.dropna(subset=['name', 'host_name'])
mediana_dzielnicy = airbnb.groupby(['town' , 'district'])['price'].transform('median')
airbnb['price'] = airbnb['price'].fillna(mediana_dzielnicy)
mediana_dzielnicy = airbnb.groupby(['town'])['price'].transform('median')
airbnb['price'] = airbnb['price'].fillna(mediana_dzielnicy)
airbnb['visited'] = airbnb['last_review'] > airbnb['listing_added']
kolumny_numeryczne = ['reviews_per_month', 'rating', 'number_of_stays', '5_stars']
airbnb[kolumny_numeryczne] = airbnb[kolumny_numeryczne].fillna(0)
# airbnb[~airbnb.isna().any(axis=1)]
airbnb

,listing_id,name,host_id,host_name,room_type,price,number_of_reviews,last_review,reviews_per_month,availability_365,rating,number_of_stays,5_stars,listing_added,latitude,longitude,town,district,visited
0,13740704,"Cozy,budget friendly, cable inc, private entra...",20583125,Michel,Private room,45.0,10,2018-12-12,0.70,85,4.100954,12.0,0.609432,2018-06-08,40.63222,-73.93398,Brooklyn,Flatlands,True
1,22005115,Two floor apartment near Central Park,82746113,Cecilia,Entire home/apt,135.0,1,2019-06-30,1.00,145,3.367600,1.2,0.746135,2018-12-25,40.78761,-73.96862,Manhattan,Upper West Side,True
2,21667615,Beautiful 1BR in Brooklyn Heights,78251,Leslie,Entire home/apt,150.0,0,NaN,0.00,65,0.000000,0.0,0.000000,2018-08-15,40.70070,-73.99517,Brooklyn,Brooklyn Heights,False
3,6425850,"Spacious, charming studio",32715865,Yelena,Entire home/apt,86.0,5,2017-09-23,0.13,0,4.763203,6.0,0.769947,2017-03-20,40.79169,-73.97498,Manhattan,Upper West Side,True
4,22986519,Bedroom on the lively Lower East Side,154262349,Brooke,Private room,160.0,23,2019-06-12,2.29,102,3.822591,27.6,0.649383,2020-10-23,40.71884,-73.98354,Manhattan,Lower East Side,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10014,22307861,Lovely 1BR Harlem apartment,16004068,Rachel,Entire home/apt,105.0,4,2018-05-28,0.21,0,4.757555,4.8,0.639223,2017-11-22,40.80379,-73.95257,Manhattan,Harlem,True
10015,953275,Apartment For Your Holidays in NYC!,4460034,Alain,Entire home/apt,125.0,50,2018-05-06,0.66,188,4.344704,60.0,0.648778,2017-10-31,40.79531,-73.93330,Manhattan,East Harlem,True
10016,3452835,"Artsy, Garden Getaway in Central Brooklyn",666862,Amy,Entire home/apt,100.0,45,2016-11-27,0.98,0,3.966214,54.0,0.631713,2016-05-24,40.68266,-73.96743,Brooklyn,Clinton Hill,True
10017,23540194,"Immaculate townhouse in Clinton Hill, Brooklyn",67176930,Sophie,Entire home/apt,450.0,2,2019-05-31,0.17,99,4.078581,2.4,0.703360,2018-11-25,40.68832,-73.96366,Brooklyn,Clinton Hill,True
10018,32876011,Private room in a perfect location in the city,59583716,Shai,Private room,90.0,1,2019-03-12,0.25,8,4.069096,1.2,0.720249,2018-09-06,40.76174,-73.96625,Manhattan,Upper East Side,True

## Faza 5 walidacja

In [128]:
bledne_daty = airbnb[(airbnb['last_review'] < airbnb['listing_added'])]
print(f"Błędy w datach: {len(bledne_daty)}")
bledny_kalendarz = airbnb[(airbnb['availability_365'] < 0) | (airbnb['availability_365'] > 365)]
print(f"Błędy w dostępności: {len(bledny_kalendarz)}")
bledne_oceny = airbnb[(airbnb['rating']  < 0) | (airbnb['rating'] > 5)]
print(f"Błędy w ocenach (rating): {len(bledne_oceny)}")
bledne_5_stars = airbnb[(airbnb['5_stars'] < 0.0) | (airbnb['5_stars'] > 1.0)]
print(f"Błędy w odsetku 5 gwiazdek: {len(bledne_5_stars)}")
bledne_ceny = airbnb[(airbnb['price'] <= 0)]
print(f"Błędy w  cenach: {len(bledne_ceny)}")
bledne_ilosc_ocen = airbnb[(airbnb['number_of_reviews'] < 0)]
print(f"Błędy w  ilosci ocen: {len(bledne_ilosc_ocen)}")

Błędy w datach: 6
Błędy w dostępności: 0
Błędy w ocenach (rating): 3
Błędy w odsetku 5 gwiazdek: 0
Błędy w  cenach: 2
Błędy w  ilosci ocen: 0

In [2]:
airbnb = airbnb.drop(index=bledne_daty.index)
airbnb = airbnb.drop(index=bledne_oceny.index)
airbnb = airbnb.drop(index=bledne_ceny.index)
# airbnb['last_review'] = airbnb['last_review'].fillna(pd.to_datetime('1970-01-01'))
airbnb.to_csv('airbnb_clean.csv', index=False)

NameError: name 'airbnb' is not defined